name: Daily and Push Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  combined:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: make
